### ISSUE TITLE
Waypoint Inspector button layout problem

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#313] opened 2017-04-24 10:21 UTC
v 1.2 (2)

The button layout in the Waypoint Inspector is wrapping to a new line. This is the first time I've seen this behavior.

![wi button layout](https://cloud.githubusercontent.com/assets/26678403/25332839/4829a87a-28a5-11e7-96df-c56c773ffdac.PNG)

**Comment by aesculus** [comment] 2017-04-24 15:04
Thanks. I think this related to that location button on the other side and globe icon slipping. I will review.

**Comment by aesculus** [comment] 2017-04-25 19:43
Fixed in V1.2 (3)

**Comment by EVGrokker** [comment] 2017-04-25 20:13
Not fixed in 1.2 (3). See attached screen shot. Notice the Waypoint Inspector is tucked under the map buttons and now constrained by Location button on right side. Is it being squeezed? If so, consider relocating Location button to right-side stack.

![waypoint inspector](https://cloud.githubusercontent.com/assets/26678403/25405663/2db6a278-29c1-11e7-9d98-1c1b896b5783.PNG)

**Comment by aesculus** [comment] 2017-04-25 20:24
Hmm. Not good. I need to snag the iPhone for a test.

**Comment by aesculus** [comment] 2017-04-25 21:33
I can't seem to find a way around having the map icons not overlay the info window. It may be a Google thing. Leave this open for now and I will continue looking for solutions.

**Comment by EVGrokker** [comment] 2017-04-25 21:35
It's only become an issue since adding the location button on the left side. How about trying location stacked on the right side to see if that helps?

**Comment by EVGrokker** [comment] 2017-04-25 21:36
Or bottom left?

**Comment by aesculus** [comment] 2017-04-25 22:32
I swapped it with the location icon and it's OK, and the location one is now down. 

I can fix it programmatically. A little worried about that but remember, we also removed the Map Type buttons so that might have something to do with it.  And before the globe button was down further.

But my bigger concern is the wrapping of the buttons. I just found something that I hope will fix that.

Try V1.2 (4)

**Comment by EVGrokker** [comment] 2017-04-25 23:08
Just installed 1.2 (5), icons are still wrapping in the waypoint inspector, the globe and map buttons still overlay the waypoint inspector.

The good news is that the location icon (top right) is now vertically aligned with the globe icon.

**Comment by aesculus** [comment] 2017-04-25 23:12
I cannot do anything right now on the overlay of the icons. Google thing.

My iPhone and iPad don't wrap the buttons.  I wonder what's going on there?

They are wrapping on the Android phone too. :-(

**Comment by EVGrokker** [comment] 2017-04-25 23:14
Did you try moving location to the stack of buttons on the right side? This wasn't an issue until we added the location button on the left side.

**Comment by aesculus** [comment] 2017-04-25 23:15
I tried swapping them but have not tried moving it over to the right.

**Comment by EVGrokker** [comment] 2017-04-25 23:17
I'll bet a pair of scissors that stacking all buttons on the right side vertically fixes it.

**Comment by EVGrokker** [comment] 2017-04-25 23:21
I'd suggest bottom right placement since it's an overlay function, like the chargers.

**Comment by aesculus** [comment] 2017-04-25 23:46
Yeah. Moving it over the right did fix it.

The issue is that Google is trying to squeeze it in between the two sets of icons, probably so it does not show there terrible overlay issue. :-)

So where do you want it? Above the supercharger icon?

**Comment by EVGrokker** [comment] 2017-04-25 23:49
It should be grouped with the charger icons since it's an overlay function. But it also recenters the map. So below the folded map, above the lightning bolt.

**Comment by EVGrokker** [comment] 2017-04-25 23:49
(like you suggested)

**Comment by aesculus** [comment] 2017-04-25 23:50
OK

Fixed again in V1.2 (6). I am not going to make a special version just for this so you will have to deal with it until the next update. :-)

**Comment by aesculus** [comment] 2017-04-26 00:12
And before you complained I went in and made them all the same width and reasonably the same height. If you want them exactly the same height they will have to follow the supercharger icon.

![image](https://cloud.githubusercontent.com/assets/283364/25412789/4dea61f6-29da-11e7-9e92-70ad8dbb5eee.png)

**Comment by EVGrokker** [comment] 2017-04-26 00:13
👍

**Closed** 2017-04-26 10:41 UTC
Labels: enhancement
