### ISSUE TITLE
Add ability to delete trip segments

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#89] opened 2017-03-31 00:05 UTC
Perhaps from Trip Segment Summary list?

Would have to deal with pulling them from the middle or worse, the start of the trip.  Might not allow them to be pulled from the start.

Could also allow the user to delete the destination/origin pair from the Infowindow like the can for supercharges and other waypoints.

**Comment by EVGrokker** [comment] 2017-03-31 11:39
Since a multi-segment trip is composed of a linked series of segments sharing hinge points, what does it mean to delete a segment? I think it means to convert the hinge point between two segments into a regular waypoint. 

Let's say that I'm planning a multi-day trip of 1000 miles starting at Home and ending at Destination. After initially creating the trip, I start figuring out where I want to charge, and where I want to spend the night. I end up with something like this:

Day 1 - 250 miles
Day 2 - 125 miles
Day 3 - 125 miles
Day 4 - 300 miles
Day 5 - 200 miles

Later I decide that I want to combine segments 2 and 3, shortening my trip by a day. From a routing perspective, nothing has changed - I'm still planning to drive the same roads, it's just a question of where the segment breaks are. So I don't want to delete the Day 2 destination, I simply want to change its status from a hinge point to a regular waypoint when joining segments 2 and 3 to become segment 2.

In that scenario, it would make sense to me to add a **Join →** function. 

Option 1) Button is displayed in waypoint info popup of a segment's destination. The meaning of that button would be 'Join this segment to the next segment, making a single segment.' If the displayed waypoint is the destination of the last segment (the ultimate destination), the button would either be grayed out or not displayed.

Option 2) Button would be exposed from the Trip Segments Summary list. Long-pressing an individual trip segment would pop up a dialog including the **Join →** button. There's an opportunity to display other segment summary info in this popup - segment mileage, time, initial and final SoC, etc.. There would be some overlap with Trip Summary and Trip Details, but I think that's OK. 

In the 5-segment example above, pressing the **Join →** button while viewing segment 2's info would cause segments 2 and 3 to be combined, preserving the hinge point, but converting it to a regular waypoint. Segments 4 and 5 would become segments 3 and 4.

From a trip management perspective, I think I'd prefer the Option 2, because you're working from a high-level overview of the trip in the Trips Segment Summary list, where you can easily toggle between segments to see their connections.

**Comment by aesculus** [comment] 2017-03-31 15:17
Sort of a reverse segmentation?  That could work too when the segment is in between the first and last.

What if we decide we want to cut the trip short and just not do the last segment? That would actually require a complete removal of the last segment. A slightly different approach?

**Comment by EVGrokker** [comment] 2017-03-31 15:24
To delete a segment in its entirety, I'd suggest left-swiping from Trip Segments Summary list.

**Comment by aesculus** [comment] 2017-03-31 15:26
Why am I not surprised. :-)

**Comment by EVGrokker** [comment] 2017-03-31 15:32
The only problem with swipe-to-delete from the Segment list… what happens if they delete an interior segment, say for example segment 2 of 3. That would imply that segment 1's destination now becomes segment 3's origin. That's a reasonable scenario. It would effectively add a new origin to segment 3, turning its previous origin into the first waypoint. 

I would suggest a confirmation dialog when deleting segments to confirm that they really intended the swipe.

**Comment by aesculus** [comment] 2017-03-31 15:34
>I would suggest a confirmation dialog when deleting segments to confirm that they really intended the swipe.
Absolutely

**Comment by aesculus** [comment] 2017-04-15 23:00
At one time I thought I supported the concept of deleting either the origin or destination of a segment pair.  The idea is that if you deleted the pseudo destination it would take out the pseudo origin it was paired with and thus join the two segments into one.

I looked and don't see that as a function but did not go into the code.

**Comment by EVGrokker** [comment] 2017-04-16 09:46
I would keep this open but suggest that it be considered for a later version.

**Comment by aesculus** [comment] 2017-04-17 00:25
I am working on an emergency solution for a guy that is planning a one month trip across the US.  He is using segments but when he decides to change them he has no way to do this without deleting the trip.

So I am altering the behavior of the Waypoint Inspector Delete button to work on the destination/origin pairs too. If the user deletes the pair it will remove those two waypoints and assign all of the waypoints to the upstream segment. It will then reorder (move up) all of the other segments.

**Comment by aesculus** [comment] 2017-04-17 05:05
In V 1.1.4 (4) I have allowed the user to delete (from the Waypoint Inspector) either the pseudo destination or pseudo origin from a pair of segments.  This essentially combines the two segments into one, by deleting the downstream segment, changing the origin/destination pair into a waypoint and reordering the trip segments.

I will leave this open until it is reviewed and confirmed appropriate.

**Comment by EVGrokker** [comment] 2017-04-17 10:24
How are you handling the hinge waypoint of a two-segment round trip?

**Comment by aesculus** [comment] 2017-04-17 17:05
There is a special flag on the Round Trip/Out and Back trips, so the Delete waypoint icon is disabled for those special pairs.

**Comment by EVGrokker** [comment] 2017-04-19 09:58
v 1.1.4 (6)
Trip: Sand Dollar Inn & Cottages, [fwbhbg441sqjx5cfjnuas]

This is a multi-segment trip:
- Seattle - Moclips WA
- Moclips - Bend OR
- Bend - Kennewick WA
- Kennewick - Ellensburg WA

Select the Bend to Kennewick segment. Touch the Kennewick destination pin. There is no option to delete this hinge pin, which would combine this segment with the next. (The delete pin is grayed out).

Select the Kennewick to Ellensburg segment. Touch the Kennewick origin pin. Now the delete pin is enabled.

Since these two actions are logically equivalent, they both should be possible.

**Comment by EVGrokker** [comment] 2017-04-19 10:04
v 1.1.4(6)
Trip: Sand Dollar Inn & Cottages, [fwbhbg441sqjx5cfjnuas]

Segment merging is not working properly.

Select the Kennewick to Ellensburg segment. Touch the Kennewick origin pin. Touch the delete pin to merge these two segments. The dialog is displayed, I touch Merge.

There is no visible change on the map. The Kennewick origin pin is still displayed in blue. The route segments have not been combined. The Trip Segments badge is still 4, not 3.

Touch the Trip Segments button. Even though the badge says 4, there are 3 segments listed, and they are the correct 3 segment names:
- Sand Dollar Inn & Cottages
- Bend
- Holiday Inn Express Ellensburg

Touch the globe icon. No refresh of the map, still shows 4 segments.
Go back to the Main screen, then Resume Trip. Now the map is missing the Kennewick - Ellensburg section of the route.
Close app. Resume Trip. Now the trip is shown with 4 segments, as originally configured before I tried merging. Trip Segments shows 4 segments as well.

**Comment by EVGrokker** [comment] 2017-04-19 10:10
Same setup, this time tried deleting the Bend OR segment as destination. That appears to work correctly. So maybe the problem is when the combined segments include the last segment.

**Comment by aesculus** [comment] 2017-04-19 15:50
I see a bug in that it allows deleting the last segments destination when it should not do that.

**Comment by aesculus** [comment] 2017-04-19 16:02
The logic for what waypoints could be deleted was wrong. It's fixed in V1.1.4 (7).

> Select the Kennewick to Ellensburg segment. Touch the Kennewick origin pin. Touch the delete pin to merge these two segments. The dialog is displayed, I touch Merge.

I see this error.

**Comment by aesculus** [comment] 2017-04-20 05:04
There were a number of errors that I found with the Merge routine.  Can you try this again with V1.1.4 (7)?

Also after merging, try segmenting again and validate the names are what you want too in both cases.

**Comment by EVGrokker** [comment] 2017-04-20 10:49
v 1.1.4 (7) is vastly improved. Segment naming looks good, the delete and merge operations seem robust. I do see an enhancement with the Delete Waypoint dialog, I'll file a separate issue for that. I think you can close this issue.

**Closed** 2017-04-20 15:38 UTC
Labels: enhancement

**Comment by aesculus** [comment] 2017-04-22 17:48
Just for a note I added the ability to delete the last segment which is not addressed by the segment merge feature. (Issue #299 )
