### ISSUE TITLE
Current Trips: Allow activating and resuming trip directly from this screen.

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#136] opened 2017-04-04 13:35 UTC
After a trip is selected, or using the current trip, the 'Activate Trip' menu item should be functionally equivalent to pressing the Resume Trip button from the Main screen, saving the user a couple of clicks.

**Comment by aesculus** [comment] 2017-04-05 04:08
I checked this out and the behavior seems as described above.  There are perhaps some timing issues at hand here.  I updated some screen change timings that might help. Reopen this issue if the problem is not resolved in V1.1.3 (4)

**Closed by aesculus** 2017-04-05 04:08 UTC
Labels: bug

**Comment by EVGrokker** [comment] 2017-04-05 12:30
I think I was expecting different behavior. 

Currently, when opening the Current Trips screen, the current trip is shown in bold. I was assuming that pressing Activate trip would simply return to the map display with the current trip still loaded. Now I see that I would have to first select it, then touch Activate to return to Plan Trip with it as the active trip.

Perhaps an additional menu item could be added here 'Resume Current Trip' to avoid the additional steps required to simply return to the current trip. The user could also click Back and then Resume Trip from the Main screen, but again, this seems like extra steps.

**Comment by aesculus** [comment] 2017-04-05 15:24
Ah. I see.

You have to press the Back button and then on the main panel Resume Trip.

If I add a Resume to the menu you have to press the Menu and then the Resume button. Nothing gained IMHO.

**Comment by EVGrokker** [comment] 2017-04-05 15:43
Let me clarify. If you're in the Current Trips menu, and you press Resume Trip from within the Current Trips menu, it would take you directly back to the Plan Trip screen, bypassing the Main screen.

**Comment by aesculus** [comment] 2017-04-05 16:14
Yes, but you still have to select the menu (one click) to get the Resume Trip, so nothing gained.

BTW I still have to pass through the main screen to get the the Plan screen but it may only appear as a flash.

So I admit physiologically your way may appear better because you don't have to consciously wait for the main screen to appear before you do the next tap.

So do you think adding the Resume Trip menu item would be more helpful? It's easy to add. I guess if I add it and you don't like it, its just as easy to remove.

**Comment by EVGrokker** [comment] 2017-04-05 16:40
To be honest, I'm generally uncomfortable with the UI in Current Trips (and Archived Trips).

The selection process is awkward. Activating a trip is awkward. Deleting multiple trips is awkward (issue #22). Renaming trips is not available (issue #94). I think too much information is initially exposed per trip, I'd rather see it collapsed.

Ideally, I'd like to see a redesigned UI. 

Adding a Resume Trip menu item would be a bandaid at best, and wouldn't really address my larger concerns with this screen.

**Comment by aesculus** [comment] 2017-04-05 16:44
I have no issues with taking a fresh look at the panel.  But keep in mind all the functions needed for trips have to take place somewhere.  Also I am not excited about making device specific UI's either just to make Joney Ive happy. :-)

**Comment by EVGrokker** [comment] 2017-04-05 16:48
Pardon my Android ignorance, I really am not familiar with its UI conventions. Does Android support swipable list items with multiple buttons when the item is swiped (e.g., Delete, Rename, Share)?

**Comment by aesculus** [comment] 2017-04-05 16:52
It can, but the UI is not the same necessarily. I (we) are going to have to do a bit of homework here.

I am all for looking into this after V1.4 is functional. That's my biggest concern right now as having to do the multiple optimizes is more confusing than anything else and it also has some issues with having to optimize twice and missing it completely.

**Comment by EVGrokker** [comment] 2017-04-05 16:57
Agreed, this is a enhancement discussion for a future major version release.

**Comment by EVGrokker** [comment] 2017-05-29 12:39
v 1.2.0 (23)

Now that you've revised the layout of the Current Trips panel, there is an opportunity to streamline the user interaction here. The most common action in this panel is 'Activate Trip'. I propose changing the UI here so that touching an individual trip summary activates it directly without having to go through the menu.

**Comment by aesculus** [comment] 2017-05-29 16:58
Implemented for phone list only on V 1.2 (24). For tablets you still have to use the menu.

Note the normal Activate in the menu is still valid too.

**Comment by EVGrokker** [comment] 2017-05-30 13:39
This is definitely an improvement, but I think it would be better if upon touching an inactive trip, it becomes the active trip (evidenced by bold text). If the user wants to go to it, they would touch Back and Resume Trip. The reasoning is that they may want to subsequently perform an action on the just-activated trip, like sharing it, archiving it, reversing it, etc.

I know there's a tug of war here with the interaction model, as the entire panel is designed on selecting an action, selecting the target, then initiating the action. I'd really like to move away from that, towards a simpler sequence: Select the target trip, select the action.

**Comment by aesculus** [comment] 2017-05-30 15:22
>  If the user wants to go to it, they would touch Back and Resume Trip. 

They would have to use Back and Resume, so two touches

>The reasoning is that they may want to subsequently perform an action on the just-activated trip, like sharing it, archiving it, reversing it, etc.

None of the actions in the menu are Active Trip based. In all cases you have to select a trip and then an action.

>I know there's a tug of war here with the interaction model, as the entire panel is designed on selecting an action, selecting the target, then initiating the action. I'd really like to move away from that, towards a simpler sequence: Select the target trip, select the action.

And don't forget that some of the actions (Delete, Archive, Compare) are multi-select. When redesigning the action feature, we have to keep that in mind. This is why it works the way it does today.

**Comment by EVGrokker** [comment] 2017-05-30 15:47
I've purposefully been avoiding posting new issues against the design of these two panels. We have a very early issue (#22) regarding using a swipe gesture to delete a trip. If/when you implement that, the entire UI here is up for redesign. I have ideas but I've been holding them.

**Comment by aesculus** [comment] 2017-05-30 16:03
OK. No rush. This was just a fairly quick way to implement a valued feature.  I think 90% of the time people would come to change trips and that is what the primary action is when you touch the trip.

I favor to keep it this way for now and revisit this when the master redesign is made later.  I really need to get back to finishing the server issue WRT charger and Min SoC so we can get this into the hands of the beta testers and users ASAP.

**Comment by EVGrokker** [comment] 2017-05-30 16:27
Agreed.

**Comment by aesculus** [comment] 2017-05-31 06:31
I updated the Current Trips for tablets to do this too in V 1.2 (25)
