### ISSUE TITLE
Auto-planned route missing charger label

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#362] opened 2017-05-02 11:41 UTC
v 1.2.0 (10)

New Trip: Fremont CA to Elko NV, Auto

The Winnemucca NV charger pin is missing its **S** label. It shows up eventually.

![missing charger label](https://cloud.githubusercontent.com/assets/26678403/25616419/b346103a-2ef9-11e7-9600-302ea63f4d82.PNG)

**Comment by aesculus** [comment] 2017-05-02 17:22
This is a dupe of #3

**Closed** 2017-05-02 17:23 UTC
Labels: bug, duplicate
