### ISSUE TITLE
Plan trip to a destination charger does not assume I will recharge at that location

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#31] opened 2017-03-25 20:32 UTC
When a segment terminates at a destination charger, the subsequent outbound trip should assume that I recharged using the destination charger. However, that SOC should be editable, since I may not have been able to recharge to my standard departure SOC.

**Comment by aesculus** [comment] 2017-03-25 20:47
This is a duplicate of https://github.com/aesculus/EVTO-App-Feedback/issues/30

**Closed** 2017-04-04 05:58 UTC
Labels: duplicate
