### ISSUE TITLE
Auto Segment Feature

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#260] opened 2017-04-17 17:19 UTC
> Last year I drove Oslo-Arezzo. The trip is approximately 2300km. I would have loved for the trip planner to suggest possible overnight stays along the way at places with destination chargers. Would have saved me from a lot of googling and calling.

There have been a number of comments about helping users figure out when and where to segment a trip.  Right now the Trip Summary shows elapsed time and the user can figure out where they might want to stop based on duration.

But there may be something more that can be done.  This thread is a discussion of those potential ideas.

**Comment by EVGrokker** [comment] 2017-04-17 20:55
Isn't this part of the same discussion started in issue #252?

**Comment by aesculus** [comment] 2017-04-17 21:03
Definitely related and should be combined. I was looking for it but could not find it

**Comment by EVGrokker** [comment] 2017-04-22 10:01
Closed, duplicate of #252.

**Closed by EVGrokker** 2017-04-22 10:01 UTC
Labels: duplicate
